# site settings
title: Modern Jive	
subtitle: University of Bristol
email: bristolleroc@gmail.com
description: A simple, bubbly and fun partner dance suitable to all sorts of music genres!
baseurl: #"/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: https://modernjive.uk # the base hostname & protocol for your site
author:
street_address: 105 Queens Road
city: Bristol
state: 
zip_code: BS8 1LN
country: United Kingdom
phone: +44 (0) 7746352343

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 10

# social settings
500px_url:
facebook_url: https://www.facebook.com/uobmodernjive
github_url: https://bristolmodernjive.github.io/
#gitlab_url: https://gitlab.com/andrewbanchich
#googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com/uobmodernjive
#linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
#pinterest_url:
#slack_url:
#twitter_url: https://twitter.com/andrewbanchich



# build settings
markdown: kramdown

sass:
  style: compressed


google_analytics: UA-174924016-1


#plugins:
 # - jekyll-analytics

#jekyll_analytics:
#  GoogleAnalytics:          # Add, if you want to track with Google Analytics
#    id: UA-174924016-1          # Required - replace with your tracking id
#    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking
